### ISSUE TITLE
Open File

### ISSUE THREAD

**Issue by lv2eof** [Nokse22/ascii-draw#10]
Hi,
I don't know if I should post this as a feature request or as a bug.
The question is about opening files.
The program works very well, does very nice drawings and they can be saved.
But if we realize that the drawing must be improved?
I haven't see a way for opening a saved drawing.
It's very strange and it's really the first time I see such a behaviour.
So I ask you to create this feature which is to be able to open a previously saved drawing.
I think that would not be very complicated.
Thanks in advance,
Luis Vital

**Comment by Nokse22** [comment]
Hi.
Right now it isn't possible to open files, but I will add this feature as soon as I can.

**Comment by lv2eof** [comment]
Hi again,
Yes, now it saves :-)
Very good and very thanks.
Just a tiny problem: If you draw something and close the application without saving, it doesn't warn.
Usually every application does that.
Thanks.
