### ISSUE TITLE
Select and move tool

### ISSUE THREAD

**Issue by Jummit** [Nokse22/ascii-draw#19]
**Is your feature request related to a problem? Please describe.**

Sometimes I have to reposition parts of the drawing, and that currently requires copying the text to another editor, editing and copying it back.

**Describe the solution you'd like**

A "select" tool which could select a rectangular area. Dragging the selected area would move it, and clicking outside would start a new selection.

**Describe alternatives you've considered**

* Using an external editor, which is cumbersome
* In some cases just resizing the canvas would help, but it only "moves" the content left or up

**Additional context**

My specific use case is UML diagrams, where it is nice to arrange class boxes so the relation is more clear.

**Comment by Nokse22** [comment]
Hello, this is definitely something I will try add.
