### ISSUE TITLE
Consider using `master` remote

### ISSUE THREAD

**Issue by TheEvilSkeleton** [Nokse22/ascii-draw#2]
Currently, the manifest uses the GNOME stable runtimes:

https://github.com/Nokse22/ascii-draw/blob/3b5d55971301d211748129f7e06084c0a5313761/io.github.nokse22.asciidraw.json#L4

I propose to use the `master` runtime from [GNOME Nightly](https://wiki.gnome.org/Apps/Nightly), as it comes with the latest updates from GTK and libadwaita. You'll be able to port to and test the latest widgets before the next stable runtime comes out.

**Comment by Nokse22** [comment]
Hi, yes, I will make a branch to start porting it to use Libadwaita 1.4 with master runtime so that as soon as it's stable I can release it.

**Comment by soumyaDghosh** [comment]
> Currently, the manifest uses the GNOME stable runtimes:
> 
> https://github.com/Nokse22/ascii-draw/blob/3b5d55971301d211748129f7e06084c0a5313761/io.github.nokse22.asciidraw.json#L4
> 
> I propose to use the `master` runtime from [GNOME Nightly](https://wiki.gnome.org/Apps/Nightly), as it comes with the latest updates from GTK and libadwaita. You'll be able to port to and test the latest widgets before the next stable runtime comes out.

I must interrupt that a dev must not, and I emphasize must not, use dev or alpha level libraries for a stable release of an app. This is a very bad practice which is kind of monopolistic, because often these libraries are hard to build from source when not build by Gnome devs themselves.

**Comment by TheEvilSkeleton** [comment]
No one's using development libraries in stable releases. This is purely used for development purposes.

**Comment by soumyaDghosh** [comment]
> No one's using development libraries in stable releases. This is purely used for development purposes.

But often that's how things escalate, like `muzika`, `symbolic-preview`, `icon-library` and many others now & before.

**Comment by TheEvilSkeleton** [comment]
What "escalates"?

**Comment by soumyaDghosh** [comment]
https://gitlab.gnome.org/World/design/icon-library/-/blob/0.0.17/meson.build#L14

**Comment by TheEvilSkeleton** [comment]
How is that relevant? If the maintainer wants to use an unstable version of a library then let them. This has nothing to do with this app.

Upscaler is almost ready and we're mainly waiting for libadwaita 1.4 to get released so that we can release a stable version. This depends on the maintainer.
