### ISSUE TITLE
Better appdata screenshots

### ISSUE THREAD

**Issue by bertob** [Nokse22/ascii-draw#20]
The current screenshots are a bit too tall, so they get very small in app store UIs. It's recommended to make the window no bigger than 1000x700 pixels, the current ones are close to 900 in height.

It also looks like they're not using the default font somehow, if I'm not mistaken it's an older version of Cantarell (IIRC unfortunately still shipped on some distros, e.g. Ubuntu) and the large text a11y setting seems to be on.

Since we're planning to use screenshots at larger sizes in curated banners and the like on Flathub in the future this stuff is becoming more important :)

**Comment by Nokse22** [comment]
You are right Tobias, the screenshots are in need for an update, also to reflect some UI change.
I forgot I had the font size increased for better visibility, but it should be Catarell regular.

Anyway, I'll update all the screenshots (also the ones from my other apps as the same font was used)
