### ISSUE TITLE
Cannot save drawing

### ISSUE THREAD

**Issue by st-thomann** [Nokse22/ascii-draw#21]
**Cannot save drawing (if installed with snap):**

**Steps To Reproduce:**
1. Install ascii-draw with snap
2. Create a picture
3. Press "Save" or "Save as"
4. You might also try to open a file
Suspicion: Wrong configuration of the snap

**Expected behaviour:**
1. Application shows a file selection box if user clicks on Save, Save as or Open file
2. Application saves or reads the data

**Screenshots if needed:**
 GLib-GIO-WARNING **: 08:03:37.156: Error creating IO channel for /proc/self/mountinfo: Permission denied (g-file-error-quark, 2)

or

Error creating IO channel for /proc/self/mountinfo: Permission denied (g-file-error-quark, 2)

**System:**
 - App version: Nokse 0.2.0

**Additional context:**

**Comment by st-thomann** [comment]
Can confirm that it works when installing with Flatpak.

By the way: Nice application! Like it.

**Comment by soumyaDghosh** [comment]
fixed it in the snaps.
