### ISSUE TITLE
Feature: Dark Mode Theme

### ISSUE THREAD

**Issue by Indyandie** [Nokse22/ascii-draw#25]
A dark mode (night mode) toggle.
- Implement a theme that is easy on the eyes for night owls and emo dudes.
- The theme can be activated through a settings dropdown, button, or shortcut key.
- BONUS: A `system` setting. Will set the theme based on the OS or DE. This is could be tricky.

**Comment by Nokse22** [comment]
Hello, now it supports the usual dark theme, but I know it's not very easy on the eyes.
What kind of theme were you thinking about? Something like sepia colors?

**Comment by Indyandie** [comment]
Oh sorry I didn't know it supported dark mode already. Where can I find the dark mode setting?

**Comment by Nokse22** [comment]
It should follow the system theme

**Comment by Indyandie** [comment]
Thank you! 🙇 It's not on automatic because I am using the flatpak. 😅

**Comment by Nokse22** [comment]
In Fedora Gnome this is implemented very seamlessly, in some DE it doesn't work as well unfortunately
