### ISSUE TITLE
The picker tool does not update the selected character

### ISSUE THREAD

**Issue by ravener** [Nokse22/ascii-draw#26]
**Describe the bug:**

**Steps To Reproduce:**
1. Select a character for the freehand brush
2. Use the picker tool and select an empty pixel
3. Go back to freehand brush and observe the previous character is still highlighted as selected but is not the active character and you have to switch to a different character first to fix it.

**Expected behaviour:**
Character selection dialogs are updated appropriately when the picker tool is used.

**Screenshots if needed:**
[Screencast from 2024-01-27 23-37-38.webm](https://github.com/Nokse22/ascii-draw/assets/31079629/679c296f-4395-4394-addc-9747d9b894ce)

**System:**
 - App version: 0.2.0 from FlatHub

**Additional context:** Debian 12 Bookworm

**Comment by Nokse22** [comment]
Hello, in the new version that will be released soon it is fixed. It will shows what character is selected in the toolbar and it won't stay selected in the character selection.
