### ISSUE TITLE
ascii-draw saves palette to `/var/data` which is only available in flatpak

### ISSUE THREAD

**Issue by Aleksanaa** [Nokse22/ascii-draw#31]
**Describe the bug:**

Ascii-draw saves palette to `/var/data`	

https://github.com/Nokse22/ascii-draw/blob/fa082de8f84f81f5c239e0aeaaf67e33ef8d4cb9/src/window.py#L269-L270

https://github.com/Nokse22/ascii-draw/blob/fa082de8f84f81f5c239e0aeaaf67e33ef8d4cb9/src/window.py#L318-L320

This will cause the program fail to start outside flatpak (and snap?), because /var isn't typically writable.

**Steps To Reproduce:**
1. Launch the program outside of flatpak
2. See the program fail to launch because it attempted to create `/var/data` which doesn't exist
3. Remove those lines
4. The program kind of works but autosaving (?) doesn't

**Expected behaviour:**
Save to `${XDG_DATA_HOME}/ascii-draw` and fallback to `${HOME}/.local/share/ascii-draw` if that environment variable isn't set.

See [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

 - App version: 0.3.0

**Additional context:**
You can close this issue if you don't want to support for package managers other than flatpak. I'll go with my workaround.

**Comment by Nokse22** [comment]
Thank you. I will fix it as soon as I have some time.

**Comment by Aleksanaa** [comment]
I've applied a temporary fix here: https://github.com/NixOS/nixpkgs/pull/300045/files

**Comment by Nokse22** [comment]
> I've applied a temporary fix here: https://github.com/NixOS/nixpkgs/pull/300045/files

Good, I'll start from that

**Comment by Nokse22** [comment]
I have fixed it, it works in Flatpak. Let me know if it works for you too.

**Comment by Aleksanaa** [comment]
It seems okay, but maybe we should get the save directory when the class is initialized, instead of querying the environment variables every time we save?

**Comment by Nokse22** [comment]
Yes, that is probably better. I just have to figure out if snaps works too, then I can make a new release.
