### ISSUE TITLE
True ASCII palette

### ISSUE THREAD

**Issue by atomikaya** [Nokse22/ascii-draw#34]
**Is your feature request related to a problem? Please describe.**
No big problem! I've used ASCII Draw on a project of mine and it has been really useful to create my interfaces.

Example:

![Capture d’écran du 2024-05-07 15-53-08](https://github.com/Nokse22/ascii-draw/assets/25960179/8d7002df-48d2-45e4-8f3c-7ba0a7a27236)

My only pet peeve is, despite the name, there is no ASCII-only palette. Extended Latin actually is extended ASCII, and the characters are in order, so once I figured it out I was ok, but it took me a while. Because I use ASCII-only for a fallback mode of my project, I had to redo a bunch of art.

**Describe the solution you'd like**

I would like, before the other palettes, an ASCII-only palette (specifically a the printable chars 36-126 that are widely accepted everywhere). This is basically a split of your Extended Latin palette in 2 parts. I also not sure the DEL char (127) should be accessible that way, as I have used it thinking it was just space before.

**Describe alternatives you've considered**

I can just let everyone figure out how your app works and hope they get it!

**Additional context**

That's it, I think. Great job :+1:

**Comment by Nokse22** [comment]
Hello, great work on those interfaces.
Thank you for letting me know. I think it totally makes sense to split it into ASCII and the extension.
I didn't realize there was the DEL char.
I will be changing that soon.
