### ISSUE TITLE
Canvas text in dark mode is black

### ISSUE THREAD

**Issue by Master811129** [Nokse22/ascii-draw#37]
**Describe the bug:**

**Steps To Reproduce:**
1. enable dark mode
2. draw something

**Expected behaviour:**
Light text in dark mode

**Screenshots if needed:**
![Screenshot_20240519_195304](https://github.com/Nokse22/ascii-draw/assets/37829730/28d53802-6bc9-45be-ac55-808d15ca97d6)

**System:**
 - App version: 0.3.0 (Snap package)

**Additional context:**
Ubuntu 23.10

**Comment by Nokse22** [comment]
Hello, does it happen always? Thanks

**Comment by Master811129** [comment]
I does look good in light mode. But always the canvas has black text so in dark mode, It's hard to figure out what you are doing. 
Switching between light and dark theme doesn't solve anything.

**Comment by Master811129** [comment]
I checked the latest version. 
![Screenshot_20240724_145015](https://github.com/user-attachments/assets/6785b48d-9649-4d7a-ad77-b3d8678e4eaf)
Now it looks fine.
