### ISSUE TITLE
Dark mode has weird contrast, and strains the eyes

### ISSUE THREAD

**Issue by orowith2os** [Nokse22/ascii-draw#4]
**Describe the bug:**

The ASCII Draw Dark mode isn't as good as it could be:
- The dark/light shadow that's applied looks fine in light mode, but looks off in the dark mode.
- The background doesn't play well with the ASCII text. 

There's also another affect it has on my eyes and perception of the app that I can't really describe.... something to do with contrast. It's causing me to have a headache. Making the background in the dark mode be less bright would help. 

We would need to sort out the white shadow around the drawing area somehow too.

**Steps To Reproduce:**
Switch ASCII Draw to Dark Mode.

**Expected behaviour:**

The dark mode would look as "good" as the light mode. 

**Screenshots if needed:**

![image](https://github.com/Nokse22/ascii-draw/assets/93224879/7d0a6fbe-3c38-4b94-8e52-5885df9bce7d)
![image](https://github.com/Nokse22/ascii-draw/assets/93224879/dfb12150-42ac-4ddb-b8f1-03179376cf5e)

**Comment by orowith2os** [comment]
Better title.

**Comment by Nokse22** [comment]
Hello, I tried to make the dark mode with less contrast, it should have a similar level of contrast to GNOME's Text Editor
 
![Screenshot from 2023-08-25 12-52-57](https://github.com/Nokse22/ascii-draw/assets/44558032/0c6fe798-f0cb-431d-ba1f-f4e6930ea532)
![Screenshot from 2023-08-25 12-52-51](https://github.com/Nokse22/ascii-draw/assets/44558032/5f78dca2-3229-4f2e-b9c2-f986958ca703)
