### ISSUE TITLE
Allow Rotating selected areas

### ISSUE THREAD

**Issue by FriederHannenheim** [Nokse22/ascii-draw#50]
It would be cool to rotate selected areas. So for example this
![image](https://github.com/user-attachments/assets/b125c76a-8987-4bc2-87ce-6feb56c93fc4)
Would become this when rotated 90° right:
![image](https://github.com/user-attachments/assets/d76a35f4-b5c6-4098-8ace-67c0a80b39bc)

**Comment by Nokse22** [comment]
Thank you for all the suggestions. How do you imagine doing this from the UI, maybe a button in the sidebar?

**Comment by FriederHannenheim** [comment]
Yeah there could be an menu in the sidebar like there is for the text or erase tools. In this menu there could be buttons for rotation and clearing text as in #51

**Comment by Nokse22** [comment]
Alright
