### ISSUE TITLE
Make artboard larger

### ISSUE THREAD

**Issue by fernstedt** [Nokse22/ascii-draw#54]
**Describe the solution you'd like**
To make the draw-space larger. 

I am designing ASCII for my python tools/github.

The space is really limted.

**Comment by Nokse22** [comment]
You can expand the drawing canvas with the button in the top right. Or do you mean something else?

**Comment by fernstedt** [comment]
Whoa that was a fast reply.

I did not even see that button. I thougt I had checked everywhere. 
Great tool

**Comment by orowith2os** [comment]
Just encountered this in trying to resize the canvas - is a Help page possible, that directs to documentation explaining how to use the app?

**Comment by Nokse22** [comment]
@orowith2os Okay, I'll make some help pages to explain.
